#! /bin/bash

git-select-checkout() {
  git -c color.ui=always branch --sort=-committerdate --format='%(HEAD) %(refname:short) %(color:green)(%(committerdate:relative))%(color:reset)' "$@" |
    grep --invert-match '\*' |
    cut -c 3- |
    fzf --ansi --preview="echo {} | cut -d \" \" -f 1 | xargs -n 1 git -c color.ui=always log" |
    cut -d " " -f 1 |
    xargs -n 1 git checkout
}
