#! /bin/bash

git-select-checkout() {
  git branch --sort=-committerdate --format='%(HEAD) %(refname:short) (%(color:green)%(committerdate:relative)%(color:reset))' |
    grep --invert-match '\*' |
    cut -c 3- |
    fzf --preview="echo {} | cut -d \" \" -f 1 | xargs -n 1 git log" |
    cut -d " " -f 1 |
    xargs -n 1 git checkout
}
